# Generated by Django 6.1 on 2026-08-22 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=150)),
                ('vagas', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Concurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=200)),
                ('orgao', models.CharField(max_length=100)),
                ('banca', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Concurso',
                'verbose_name_plural': 'Concursos',
                'ordering': ('orgao', 'nome'),
                'constraints': [models.UniqueConstraint(fields=('orgao', 'nome'), name='unico_concurso_por_orgao')],
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=150)),
                ('peso', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='editais.cargo')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Edital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ano', models.PositiveIntegerField()),
                ('data_prova', models.DateField(blank=True, null=True)),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='editais_pdfs/%Y/%m/')),
                ('concurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editais', to='editais.concurso')),
            ],
            options={
                'verbose_name': 'Edital',
                'verbose_name_plural': 'Editais',
                'ordering': ('-ano',),
            },
        ),
        migrations.AddField(
            model_name='cargo',
            name='edital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='editais.edital'),
        ),
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=255)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicos', to='editais.disciplina')),
            ],
            options={
                'verbose_name': 'Tópico',
                'verbose_name_plural': 'Tópicos',
                'ordering': ('disciplina', 'ordem'),
            },
        ),
        migrations.AddConstraint(
            model_name='disciplina',
            constraint=models.UniqueConstraint(fields=('cargo', 'nome'), name='unica_disciplina_por_cargo'),
        ),
        migrations.AddConstraint(
            model_name='edital',
            constraint=models.UniqueConstraint(fields=('concurso', 'ano'), name='unico_edital_por_ano'),
        ),
        migrations.AddConstraint(
            model_name='cargo',
            constraint=models.UniqueConstraint(fields=('edital', 'nome'), name='unico_cargo_por_edital'),
        ),
        migrations.AddIndex(
            model_name='topico',
            index=models.Index(fields=['disciplina', 'ordem'], name='idx_topico_disciplina_ordem'),
        ),
        migrations.AddConstraint(
            model_name='topico',
            constraint=models.UniqueConstraint(fields=('disciplina', 'nome'), name='unico_topico_por_disciplina'),
        ),
    ]
