# Generated by Django 6.1 on 2026-08-22 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editais', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressoTopico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('NAO_INICIADO', 'Não Iniciado'), ('TEORIA', 'Teoria'), ('REVISAO', 'Revisão'), ('CONCLUIDO', 'Concluído')], default='NAO_INICIADO', max_length=20)),
                ('nivel_dominio', models.IntegerField(blank=True, choices=[(1, 'Difícil'), (2, 'Médio'), (3, 'Fácil')], null=True)),
                ('data_ultima_revisao', models.DateField(blank=True, null=True)),
                ('data_proxima_revisao', models.DateField(blank=True, null=True)),
                ('topico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressos', to='editais.topico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progresso de tópico',
                'verbose_name_plural': 'Progressos de tópicos',
                'ordering': ('data_proxima_revisao',),
                'indexes': [models.Index(fields=['usuario', 'data_proxima_revisao'], name='idx_progresso_usuario_revisao'), models.Index(fields=['usuario', 'status'], name='idx_progresso_usuario_status')],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'topico'), name='unico_progresso_por_usuario_topico')],
            },
        ),
        migrations.CreateModel(
            name='SessaoDeEstudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tempo_minutos', models.PositiveIntegerField()),
                ('questoes_feitas', models.PositiveIntegerField(default=0)),
                ('questoes_acertadas', models.PositiveIntegerField(default=0)),
                ('data_sessao', models.DateTimeField(auto_now_add=True)),
                ('topico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='editais.topico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sessão de estudo',
                'verbose_name_plural': 'Sessões de estudo',
                'ordering': ('-data_sessao',),
                'indexes': [models.Index(fields=['usuario', '-data_sessao'], name='idx_sessao_usuario_data')],
                'constraints': [models.CheckConstraint(condition=models.Q(('questoes_acertadas__lte', models.F('questoes_feitas'))), name='acertos_nao_excedem_questoes'), models.CheckConstraint(condition=models.Q(('tempo_minutos__gt', 0)), name='tempo_sessao_positivo')],
            },
        ),
    ]
