# Generated by Django 6.1 on 2026-08-22 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoStripeProcessado',
            fields=[
                ('evento_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
                ('processado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evento Stripe processado',
                'verbose_name_plural': 'Eventos Stripe processados',
                'ordering': ('-processado_em',),
            },
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=50)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stripe_price_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'ordering': ('preco',),
            },
        ),
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('INATIVA', 'Inativa'), ('ATIVA', 'Ativa'), ('CANCELADA', 'Cancelada')], default='INATIVA', max_length=20)),
                ('stripe_customer_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('data_expiracao', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assinatura', to=settings.AUTH_USER_MODEL)),
                ('plano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assinaturas', to='assinaturas.plano')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
                'ordering': ('-criado_em',),
                'indexes': [models.Index(fields=['status', 'data_expiracao'], name='idx_assinatura_status_exp')],
            },
        ),
    ]
